# //createScream
POST https://asia-east2-krowten-ffb6f.cloudfunctions.net/api/scream
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjQ5ZTg4YzUzNzYxOTk2YTczNjIzZjE5MWQ1MTJkMmI0N2RmODAyYTEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20va3Jvd3Rlbi1mZmI2ZiIsImF1ZCI6Imtyb3d0ZW4tZmZiNmYiLCJhdXRoX3RpbWUiOjE1OTc1MDMxOTksInVzZXJfaWQiOiJWRmhhelFKZTJqaEtXSWMwcE1GTGJ0ekZqcTQyIiwic3ViIjoiVkZoYXpRSmUyamhLV0ljMHBNRkxidHpGanE0MiIsImlhdCI6MTU5NzUwMzE5OSwiZXhwIjoxNTk3NTA2Nzk5LCJlbWFpbCI6InVzZXIzQGVtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJ1c2VyM0BlbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.tCwAIbcK9v9WhNb5oua53tb9PFkdceXNYn3cd4Qx9BBDkWwCNrr7d57SGbrz6MgcJnkdh2LUAYRS1zFaArJQLl4v9S-JNX_vhP4M-w5iUQ39yoAL63vHj2JB5Ycvjcl64CYnE2Y7BmLVe4ZLFA1PKAxVChVyubPUMJLgzIBX7mZPD7zwsOi1nFegyUg5qaYgQOMD8tn08oq9qEmYZpBNyoxq70ltfgGNtIeBNx-Ub3O3RwV_2F9A5wnA0ajgyQuwLMUIL7KcLltGrYDxZl0U8Dvm0AGpPLhclGS7Gislq2XIWHXMELJK5thcCEOAkNsDAG9zkJpsyDbX3l6y1ljWWg

{
  "body": ""
}

# POST http://localhost:5000/krowten-ffb6f/asia-east2/api/scream
# content-type: application/json
# Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImFmMDg2ZmE4Y2Q5NDFlMDY3ZTc3NzNkYmIwNDcxMjAxMTBlMDA1NGEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20va3Jvd3Rlbi1mZmI2ZiIsImF1ZCI6Imtyb3d0ZW4tZmZiNmYiLCJhdXRoX3RpbWUiOjE1OTY4MTQxNDksInVzZXJfaWQiOiJrZTRDM0JNNmJTU091MGZNUmtkcE5pcWsxT1gyIiwic3ViIjoia2U0QzNCTTZiU1NPdTBmTVJrZHBOaXFrMU9YMiIsImlhdCI6MTU5NjgxNDE0OSwiZXhwIjoxNTk2ODE3NzQ5LCJlbWFpbCI6InVzZXJAZW1haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbInVzZXJAZW1haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.QRIRabEdfoNFrRLWbFDn7A840iiArDi0BdZVnPd1OBhPGYvKqf9guHybZFMc66Xzf3LKqCkJNBaZ1GF1UUKNnC801XVCjJcHp24OjFb2XVz4dmtn_XYizG5750IQYM2GBAPhRctGG_YDQEHB9ZEU9K4ENQfDdxm0Rkf1pfX12Nxf0h7T2ubxl18y2wRZL-rEgHJc_N97ehO4S2pVgy8ln9R8IbW1ubFot7hYHj_m5y8DMwMT6DCi7Y8uhpd6p7zVc4NjBWeA5uM6KR0DwhamTyxX4jJUD7SFy6u6tkwP3iCFhoD21g2Bu_k-L1tMsIamPPAnHnRz-ZXiUFOI-vZMsg

# {
#   "body": "Another scream submitted"
# }

//after making API app
# GET https://asia-east2-krowten-ffb6f.cloudfunctions.net/api/screams