//createScream
# POST https://asia-east2-krowten-ffb6f.cloudfunctions.net/api/scream
# content-type: application/json

# {
#   "body": "Scream via API",
#   "userHandle": "new"
# }

//after making API app
GET https://asia-east2-krowten-ffb6f.cloudfunctions.net/api/screams