# //createScream
POST https://asia-east2-krowten-ffb6f.cloudfunctions.net/api/signup
content-type: application/json

{
  "email": "",
  "password": "",
  "confirmPassword": "",
  "handle": ""
}

# POST http://localhost:5000/krowten-ffb6f/asia-east2/api/scream
# content-type: application/json
# Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImFmMDg2ZmE4Y2Q5NDFlMDY3ZTc3NzNkYmIwNDcxMjAxMTBlMDA1NGEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20va3Jvd3Rlbi1mZmI2ZiIsImF1ZCI6Imtyb3d0ZW4tZmZiNmYiLCJhdXRoX3RpbWUiOjE1OTY4MTQxNDksInVzZXJfaWQiOiJrZTRDM0JNNmJTU091MGZNUmtkcE5pcWsxT1gyIiwic3ViIjoia2U0QzNCTTZiU1NPdTBmTVJrZHBOaXFrMU9YMiIsImlhdCI6MTU5NjgxNDE0OSwiZXhwIjoxNTk2ODE3NzQ5LCJlbWFpbCI6InVzZXJAZW1haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbInVzZXJAZW1haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.QRIRabEdfoNFrRLWbFDn7A840iiArDi0BdZVnPd1OBhPGYvKqf9guHybZFMc66Xzf3LKqCkJNBaZ1GF1UUKNnC801XVCjJcHp24OjFb2XVz4dmtn_XYizG5750IQYM2GBAPhRctGG_YDQEHB9ZEU9K4ENQfDdxm0Rkf1pfX12Nxf0h7T2ubxl18y2wRZL-rEgHJc_N97ehO4S2pVgy8ln9R8IbW1ubFot7hYHj_m5y8DMwMT6DCi7Y8uhpd6p7zVc4NjBWeA5uM6KR0DwhamTyxX4jJUD7SFy6u6tkwP3iCFhoD21g2Bu_k-L1tMsIamPPAnHnRz-ZXiUFOI-vZMsg

# {
#   "body": "Another scream submitted"
# }

//after making API app
# GET https://asia-east2-krowten-ffb6f.cloudfunctions.net/api/screams